### ISSUE TITLE
ublock

### ISSUE THREAD

**Issue by endanger** [grobgl/adblock-filters#1]
Hi, 
thanks for this filters. I would like to test it with ublock origin, but I have a problem were I add this list. can you please fill the do to?
Thank you!

**Comment by grobgl** [comment]
Thanks for the interest! I should let you know that these filters are meant for my personal use as they are rather opinionated (e.g. blocking out entire sections from news websites).

To install the filters, you need to add them as 3rd party filters to uBlock (navigate to _uBlock Dashboard_ - _3rd Party filters_, then insert the raw file URL into the text box at the bottom of the page and click _Update Now_). You can use the raw file URLs for:
- all filters at once: `https://raw.githubusercontent.com/grobgl/adblock-filters/master/filters-combined.txt`
- or for selected filters only (from the [filters folder](https://github.com/grobgl/adblock-filters/tree/master/filters)). E.g. for `newyorker.com`, use `https://raw.githubusercontent.com/grobgl/adblock-filters/master/filters/newyorker.com.txt`

Feel free to fork this repository to make your own customisations.

**Comment by endanger** [comment]
Thank you!! 👍
